/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type $defs = Record<string, never>
export interface components {
  headers: never
  parameters: {
    /** @example 4bc8892a017a3c0f92000002 */
    AccountObjectId: string
    Language: string
    /** @example 5854 */
    ListId: number
    Page: number
    SortByCreatedAt: 'created_at.asc' | 'created_at.desc'
  }
  pathItems: never
  requestBodies: never
  responses: never
  schemas: {
    AccountListSummary: {
      /** @example 4bc8892a017a3c0f92000002 */
      account_object_id?: string
      /**
       * @default 0
       * @example 0
       */
      adult: number
      /**
       * @default 0
       * @example 7.90183
       */
      average_rating: number
      /** @example 2019-08-27 15:13:15 */
      created_at?: string
      /** @example  */
      description?: string
      /**
       * @default 0
       * @example 0
       */
      featured: number
      /**
       * @default 0
       * @example 120174
       */
      id: number
      /** @example en */
      iso_639_1?: string
      /** @example US */
      iso_3166_1?: string
      /** @example Test Alpha Sort */
      name?: string
      /**
       * @default 0
       * @example 6
       */
      number_of_items: number
      /**
       * @default 0
       * @example 0
       */
      public: number
      /** @example 586453267 */
      revenue?: string
      /**
       * @default 0
       * @example 644
       */
      runtime: number
      /**
       * @default 0
       * @example 7
       */
      sort_by: number
      /** @example 2023-05-05 16:49:11 */
      updated_at?: string
    }
    ItemOperationResult: {
      /**
       * @default 0
       * @example 550
       */
      media_id: number
      /** @example movie */
      media_type?: string
      /**
       * @default true
       * @example true
       */
      success: boolean
    }
    ListDetails: {
      /**
       * @default 0
       * @example 6.7
       */
      average_rating: number
      /** @example /kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg */
      backdrop_path?: string
      /** @description Map of `media_type:media_id` keys to comment values */
      comments?: {
        [key: string]: unknown
      }
      created_by?: {
        /** @example /xy44UvpbTgzs9kWmp4C3fEaCl5h.png */
        avatar_path?: string
        /** @example c9e9fc152ee756a900db85757c29815d */
        gravatar_hash?: string
        /** @example 4bc8892a017a3c0f92000002 */
        id?: string
        /** @example Travis Bell */
        name?: string
        /** @example travisbell */
        username?: string
      }
      /** @example The idea behind this list is to collect the live action comic book movies from within the Marvel franchise. */
      description?: string
      /**
       * @default 0
       * @example 1
       */
      id: number
      /** @example en */
      iso_639_1?: string
      /** @example US */
      iso_3166_1?: string
      /**
       * @default 0
       * @example 69
       */
      item_count: number
      /** @example The Marvel Universe */
      name?: string
      object_ids?: Record<string, never>
      /**
       * @default 0
       * @example 1
       */
      page: number
      /** @example /coJVIUEOToAEGViuhclM7pXC75R.jpg */
      poster_path?: string
      /**
       * @default true
       * @example true
       */
      public: boolean
      results?: components['schemas']['MovieResult'][]
      /**
       * @default 0
       * @example 40672159319
       */
      revenue: number
      /**
       * @default 0
       * @example 8070
       */
      runtime: number
      /** @example primary_release_date.desc */
      sort_by?: string
      /**
       * @default 0
       * @example 4
       */
      total_pages: number
      /**
       * @default 0
       * @example 69
       */
      total_results: number
    }
    MovieResult: {
      /**
       * @default true
       * @example false
       */
      adult: boolean
      /** @example /9sfVyE3sP2dkCwDyV7UlYP5TAAR.jpg */
      backdrop_path?: string
      genre_ids?: number[]
      /**
       * @default 0
       * @example 823754
       */
      id: number
      /** @example movie */
      media_type?: string
      /** @example en */
      original_language?: string
      /** @example Bo Burnham: Inside */
      original_title?: string
      overview?: string
      /**
       * @default 0
       * @example 11.904
       */
      popularity: number
      /** @example /ku1UvTWYvhFQbSesOD6zteY7bXT.jpg */
      poster_path?: string
      /** @example 2021-07-22 */
      release_date?: string
      /** @example Bo Burnham: Inside */
      title?: string
      /**
       * @default true
       * @example false
       */
      video: boolean
      /**
       * @default 0
       * @example 8.178
       */
      vote_average: number
      /**
       * @default 0
       * @example 352
       */
      vote_count: number
    }
    RatedMovieResult: components['schemas']['MovieResult'] & {
      account_rating?: {
        /** @example 2012-02-15T15:18:04.000Z */
        created_at?: string
        /**
         * @default 0
         * @example 8
         */
        value: number
      }
    }
    RatedTVResult: components['schemas']['TVResult'] & {
      account_rating?: {
        /** @example 2013-10-10T21:03:56.499Z */
        created_at?: string
        /**
         * @default 0
         * @example 9
         */
        value: number
      }
    }
    RAW_BODY: {
      /**
       * Format: json
       * @description Raw JSON body
       */
      RAW_BODY?: string
    }
    StatusResponse: {
      /** @example 1 */
      status_code: number
      /** @example Success. */
      status_message?: string
      /** @example true */
      success: boolean
    }
    TVResult: {
      /**
       * @default true
       * @example false
       */
      adult: boolean
      /** @example /bsNm9z2TJfe0WO3RedPGWQ8mG1X.jpg */
      backdrop_path?: string
      /** @example 2008-01-20 */
      first_air_date?: string
      genre_ids?: number[]
      /**
       * @default 0
       * @example 1396
       */
      id: number
      /** @example tv */
      media_type?: string
      /** @example Breaking Bad */
      name?: string
      origin_country?: string[]
      /** @example en */
      original_language?: string
      /** @example Breaking Bad */
      original_name?: string
      overview?: string
      /**
       * @default 0
       * @example 255.118
       */
      popularity: number
      /** @example /ggFHVNu6YYI5L9pCfOacjizRGt.jpg */
      poster_path?: string
      /**
       * @default 0
       * @example 8.879
       */
      vote_average: number
      /**
       * @default 0
       * @example 11625
       */
      vote_count: number
    }
  }
}
export interface operations {
  'account-favorite-movies': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 4bc8892a017a3c0f92000002 */
        account_object_id: components['parameters']['AccountObjectId']
      }
      query?: {
        language?: components['parameters']['Language']
        page?: components['parameters']['Page']
        sort_by?: components['parameters']['SortByCreatedAt']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            page: number
            results?: components['schemas']['MovieResult'][]
            /**
             * @default 0
             * @example 4
             */
            total_pages: number
            /**
             * @default 0
             * @example 80
             */
            total_results: number
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'account-favorite-tv': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 4bc8892a017a3c0f92000002 */
        account_object_id: components['parameters']['AccountObjectId']
      }
      query?: {
        language?: components['parameters']['Language']
        page?: components['parameters']['Page']
        sort_by?: components['parameters']['SortByCreatedAt']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            page: number
            results?: components['schemas']['TVResult'][]
            /**
             * @default 0
             * @example 4
             */
            total_pages: number
            /**
             * @default 0
             * @example 68
             */
            total_results: number
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'account-lists': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 4bc8892a017a3c0f92000002 */
        account_object_id: components['parameters']['AccountObjectId']
      }
      query?: {
        page?: components['parameters']['Page']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            page: number
            results?: components['schemas']['AccountListSummary'][]
            /**
             * @default 0
             * @example 2
             */
            total_pages: number
            /**
             * @default 0
             * @example 25
             */
            total_results: number
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'account-movie-recommendations': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 4bc8892a017a3c0f92000002 */
        account_object_id: components['parameters']['AccountObjectId']
      }
      query?: {
        language?: components['parameters']['Language']
        page?: components['parameters']['Page']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            page: number
            results?: components['schemas']['MovieResult'][]
            /**
             * @default 0
             * @example 4
             */
            total_pages: number
            /**
             * @default 0
             * @example 80
             */
            total_results: number
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'account-movie-watchlist': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 4bc8892a017a3c0f92000002 */
        account_object_id: components['parameters']['AccountObjectId']
      }
      query?: {
        language?: components['parameters']['Language']
        page?: components['parameters']['Page']
        sort_by?: components['parameters']['SortByCreatedAt']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            page: number
            results?: components['schemas']['MovieResult'][]
            /**
             * @default 0
             * @example 4
             */
            total_pages: number
            /**
             * @default 0
             * @example 80
             */
            total_results: number
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'account-rated-movies': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 4bc8892a017a3c0f92000002 */
        account_object_id: components['parameters']['AccountObjectId']
      }
      query?: {
        language?: components['parameters']['Language']
        page?: components['parameters']['Page']
        sort_by?: components['parameters']['SortByCreatedAt']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            page: number
            results?: components['schemas']['RatedMovieResult'][]
            /**
             * @default 0
             * @example 47
             */
            total_pages: number
            /**
             * @default 0
             * @example 940
             */
            total_results: number
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'account-rated-tv': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 4bc8892a017a3c0f92000002 */
        account_object_id: components['parameters']['AccountObjectId']
      }
      query?: {
        language?: components['parameters']['Language']
        page?: components['parameters']['Page']
        sort_by?: components['parameters']['SortByCreatedAt']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            page: number
            results?: components['schemas']['RatedTVResult'][]
            /**
             * @default 0
             * @example 15
             */
            total_pages: number
            /**
             * @default 0
             * @example 291
             */
            total_results: number
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'account-tv-recommendations': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 4bc8892a017a3c0f92000002 */
        account_object_id: components['parameters']['AccountObjectId']
      }
      query?: {
        language?: components['parameters']['Language']
        page?: components['parameters']['Page']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            page: number
            results?: components['schemas']['TVResult'][]
            /**
             * @default 0
             * @example 4
             */
            total_pages: number
            /**
             * @default 0
             * @example 80
             */
            total_results: number
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'account-tv-watchlist': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 4bc8892a017a3c0f92000002 */
        account_object_id: components['parameters']['AccountObjectId']
      }
      query?: {
        language?: components['parameters']['Language']
        page?: components['parameters']['Page']
        sort_by?: components['parameters']['SortByCreatedAt']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            page: number
            results?: components['schemas']['TVResult'][]
            /**
             * @default 0
             * @example 4
             */
            total_pages: number
            /**
             * @default 0
             * @example 80
             */
            total_results: number
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'auth-create-access-token': {
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RAW_BODY']
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCIdIkpXVCJ9... */
            access_token?: string
            /** @example 4bc8892a017a3c0z92001001 */
            account_id?: string
            /**
             * @default 0
             * @example 1
             */
            status_code: number
            /** @example Success. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'auth-create-request-token': {
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RAW_BODY']
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /** @example eyJhbGciOiJIfsISNiIaInR5cCI6IkpXVCJ9... */
            request_token?: string
            /**
             * @default 0
             * @example 1
             */
            status_code: number
            /** @example Success. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'auth-logout': {
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RAW_BODY']
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 13
             */
            status_code: number
            /** @example The item/record was deleted successfully. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'list-add-items': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 5854 */
        list_id: components['parameters']['ListId']
      }
      query?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RAW_BODY']
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            results?: components['schemas']['ItemOperationResult'][]
            /**
             * @default 0
             * @example 1
             */
            status_code: number
            /** @example Success. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'list-clear': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 5854 */
        list_id: components['parameters']['ListId']
      }
      query?: never
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 10
             */
            id: number
            /**
             * @default 0
             * @example 1
             */
            items_deleted: number
            /**
             * @default 0
             * @example 1
             */
            status_code: number
            /** @example Success. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'list-create': {
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RAW_BODY']
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 5854
             */
            id: number
            /**
             * @default 0
             * @example 1
             */
            status_code: number
            /** @example The item/record was created successfully. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'list-delete': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 5854 */
        list_id: components['parameters']['ListId']
      }
      query?: never
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 13
             */
            status_code: number
            /** @example The item/record was deleted successfully. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'list-details': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 5854 */
        list_id: components['parameters']['ListId']
      }
      query?: {
        language?: components['parameters']['Language']
        page?: components['parameters']['Page']
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': components['schemas']['ListDetails']
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'list-item-status': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 5854 */
        list_id: components['parameters']['ListId']
      }
      query: {
        /** @example 99861 */
        media_id: number
        media_type: '' | 'movie' | 'tv'
      }
    }
    requestBody?: never
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 1
             */
            id: number
            /**
             * @default 0
             * @example 99861
             */
            media_id: number
            /** @example movie */
            media_type?: string
            /**
             * @default 0
             * @example 1
             */
            status_code: number
            /** @example Success. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'list-remove-items': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 5854 */
        list_id: components['parameters']['ListId']
      }
      query?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RAW_BODY']
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            results?: components['schemas']['ItemOperationResult'][]
            /**
             * @default 0
             * @example 1
             */
            status_code: number
            /** @example Success. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'list-update': {
    parameters: {
      cookie?: never
      header?: never
      path: {
        /** @example 5854 */
        list_id: components['parameters']['ListId']
      }
      query?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RAW_BODY']
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 12
             */
            status_code: number
            /** @example The item/record was updated successfully. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
  'list-update-items': {
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RAW_BODY']
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            results?: components['schemas']['ItemOperationResult'][]
            /**
             * @default 0
             * @example 1
             */
            status_code: number
            /** @example Success. */
            status_message?: string
            /**
             * @default true
             * @example true
             */
            success: boolean
          }
        }
        headers: {
          [name: string]: unknown
        }
      }
    }
  }
}
export interface paths {
  '/4/account/{account_object_id}/lists': {
    delete?: never
    /**
     * Lists
     * @description Get the custom lists that a user has created.
     */
    get: operations['account-lists']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/account/{account_object_id}/movie/favorites': {
    delete?: never
    /**
     * Favorite Movies
     * @description Get a users list of favourite movies.
     */
    get: operations['account-favorite-movies']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/account/{account_object_id}/movie/rated': {
    delete?: never
    /**
     * Rated Movies
     * @description Get a users rated movies.
     */
    get: operations['account-rated-movies']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/account/{account_object_id}/movie/recommendations': {
    delete?: never
    /**
     * Recommended Movies
     * @description Get a users list of recommended movies.
     */
    get: operations['account-movie-recommendations']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/account/{account_object_id}/movie/watchlist': {
    delete?: never
    /**
     * Watchlist Movies
     * @description Get a users movie watchlist.
     */
    get: operations['account-movie-watchlist']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/account/{account_object_id}/tv/favorites': {
    delete?: never
    /**
     * Favorite TV Shows
     * @description Get a users list of favourite TV shows.
     */
    get: operations['account-favorite-tv']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/account/{account_object_id}/tv/rated': {
    delete?: never
    /**
     * Rated TV Shows
     * @description Get a users rated TV shows.
     */
    get: operations['account-rated-tv']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/account/{account_object_id}/tv/recommendations': {
    delete?: never
    /**
     * Recommended TV Shows
     * @description Get a users list of recommended TV shows.
     */
    get: operations['account-tv-recommendations']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/account/{account_object_id}/tv/watchlist': {
    delete?: never
    /**
     * Watchlist TV Shows
     * @description Get a users TV watchlist.
     */
    get: operations['account-tv-watchlist']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/auth/access_token': {
    /**
     * Logout
     * @description Log out of a session. Invalidates the user access token.
     */
    delete: operations['auth-logout']
    get?: never
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    /**
     * Create Access Token
     * @description Step 3 of the user auth flow. Exchanges an approved `request_token` for a permanent `access_token`. Also returns the user's v4 `account_id` (string).
     */
    post: operations['auth-create-access-token']
    put?: never
    trace?: never
  }
  '/4/auth/request_token': {
    delete?: never
    get?: never
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    /**
     * Create Request Token
     * @description Step 1 of the user auth flow. Returns a temporary `request_token`. Direct the user to `https://www.themoviedb.org/auth/access?request_token={request_token}` to approve it. Unused tokens expire after 15 minutes.
     */
    post: operations['auth-create-request-token']
    put?: never
    trace?: never
  }
  '/4/list': {
    delete?: never
    get?: never
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    /**
     * Create
     * @description Create a new list.
     */
    post: operations['list-create']
    put?: never
    trace?: never
  }
  '/4/list/{list_id}': {
    delete?: never
    /**
     * Details
     * @description Retrieve a list by id.
     */
    get: operations['list-details']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    /**
     * Update
     * @description Update the details of a list.
     */
    put: operations['list-update']
    trace?: never
  }
  '/4/list/{list_id}/clear': {
    delete?: never
    /**
     * Clear
     * @description Clear all of the items on a list.
     */
    get: operations['list-clear']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/list/{list_id}/item_status': {
    delete?: never
    /**
     * Item Status
     * @description Check if an item is on a list.
     */
    get: operations['list-item-status']
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
  '/4/list/{list_id}/items': {
    /**
     * Remove Items
     * @description Remove items from a list.
     */
    delete: operations['list-remove-items']
    get?: never
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    /**
     * Add Items
     * @description Add items to a list.
     */
    post: operations['list-add-items']
    /**
     * Update Items
     * @description Update an individual item on a list.
     */
    put: operations['list-update-items']
    trace?: never
  }
  '/4/{list_id}': {
    /**
     * Delete
     * @description Delete a list.
     */
    delete: operations['list-delete']
    get?: never
    head?: never
    options?: never
    parameters: {
      cookie?: never
      header?: never
      path?: never
      query?: never
    }
    patch?: never
    post?: never
    put?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
